# Generated by Django 3.1.2 on 2020-10-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GhostPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_boast', models.BooleanField(default=True)),
                ('content', models.CharField(max_length=200)),
                ('up_votes', models.IntegerField(default=0)),
                ('down_votes', models.IntegerField(default=0)),
                ('posted_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
